# Generated by Django 5.0 on 2025-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
