# Generated by Django 5.2.4 on 2025-07-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
