# Generated by Django 5.0 on 2025-07-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='check_again',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='initial_real_disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_postponded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='testes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
